version: 2
jobs:
  build:
    working_directory: ~/prueba01
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: build
          enviroment:
            NODE_ENV: test
            BASE_API_URL: https://localhost:8081
          command: 'npm run build'
      - run:
          name: test
          command: 'npm test'
